M48
; DRILL file {KiCad 6.0.6+dfsg-1} date Fri 08 Jul 2022 04:57:31 PM CDT
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2022-07-08T16:57:31-05:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,6.0.6+dfsg-1
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0787
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.1260
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T3C0.6260
%
G90
G05
T1
X3.8343Y-2.2343
X4.3657Y-2.2343
X4.3657Y-2.7657
X4.6343Y-2.2343
X4.6343Y-2.7657
X5.1657Y-2.7657
T2
X2.0Y-2.0
X2.0Y-5.0
X3.7Y-3.5
X5.3Y-3.5
X7.0Y-2.0
X7.0Y-5.0
T3
X4.1Y-2.5
X4.9Y-2.5
T0
M30
